# This file is overriding the UI settings
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Ensure we're using npm, not bun
  USE_NPM_INSTALL = "true"
  # Add cache settings for faster builds
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_BUN = "false"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  # Remove the esbuild binary path - let Netlify handle it
  # ESBUILD_BINARY_PATH = "/opt/build/repo/node_modules/@netlify/esbuild-linux-64/bin/esbuild"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS for all requests with proper certificates
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Cache-Control = "public, max-age=0, must-revalidate"

# SSL settings
[dev]
  https = true

# Add plugin configuration directly in toml file
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  [plugins.inputs]
    includeModules = ["sharp"]
