# This file is overriding the UI settings
[build]
  command = "mkdir -p src/lib && echo 'import { type ClassValue, clsx } from \"clsx\"; import { twMerge } from \"tailwind-merge\"; export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)) }' > src/lib/utils.ts && npm install --legacy-peer-deps && npm run build || (find src -type f -name \"*.tsx\" -exec grep -l \"ChartBar\\|ChartBarIncreasing\" {} \\; | xargs cat && exit 1)"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  # Ensure we're using npm, not bun
  USE_NPM_INSTALL = "true"
  # Add cache settings for faster builds
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_BUN = "false"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  # Force resolution of dependencies
  ROLLUP_USE_NODE_RESOLVE = "true"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS for all requests with proper certificates
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Cache-Control = "public, max-age=0, must-revalidate"

# SSL settings
[dev]
  https = true
