
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Add a longer build timeout
  NETLIFY_BUILD_LIFECYCLE_TIMEOUT = "900"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS for all requests with proper certificates
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "User-Agent"

# SSL settings
[dev]
  https = true

# Handling large builds
[functions]
  node_bundler = "esbuild"
